repos:
  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v0.15.1
    hooks:
    - id: stylua-github
  - repo: https://github.com/Calinou/pre-commit-luacheck
    rev: v1.0.0
    hooks:
    - id: luacheck
