site_name: Jean-Lua Library
site_url: https://example.com/
nav:
    - Home: index.md
    - Usage:
        - usage/_index.md
        - Object: usage/object.md
        - Functional: usage/functional.md
    - ...
docs_dir: doc
edit_uri: ""
repo_url: https://github.com/jean-loutre/jean-lua.git
site_dir: .build/doc
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight: { anchor_linenums: true}
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed: {alternate_style: true }
  - tables
theme:
  name: material
  features:
    - content.tabs.link
    - header.autohide
    - navigation.instant
    - navigation.indexes
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - navigation.top
  palette: 
    - scheme: default
      primary: white
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - search
  - awesome-pages
  - section-index
